'use client';

// A custom React hook that manages a WebSocket connection for a single player in a group lobby. 
// It connects, listens for server events, and returns reactive state that the component can render.
import { useEffect, useState } from 'react';
import { io } from 'socket.io-client';
import { Game } from '../types';

interface GroupSocketState {
  pendingGames: Game[];
  startedGame: Game | null;
  isConnected: boolean;
}

// socketRef is generated by useRef instead of useState, since the object is not rendered, 
// it is infrastructure and only needs to be referenced
export function useGroupSocket(groupId: number, playerId: number) {
  const [state, setState] = useState<GroupSocketState>({
    pendingGames: [],
    startedGame: null,
    isConnected: false,
  });

  // effect runs on mount. active is a guard against the component unmounting
  // while socket event is in flight. Every event handler checks against !active
  // before touching state
  useEffect(() => {
    if (!groupId || !playerId) return;

    let active = true;

    const socket = io(
      process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000',
      {
        transports: ['websocket'],
      },
    );
    // On successful connection, the client immediately emits joinGroup to the server.
    // This tells the NestJS Gateway to put this socket into a room named after the group. 
    // From that point on, the server can broadcast to everyone in that room without knowing individual socket IDs.
    socket.on('connect', () => {
      if (!active) return;
      setState((s) => ({ ...s, isConnected: true }));
      socket.emit('joinGroup', { groupId, playerId });
    });

    socket.on('disconnect', () => {
      if (!active) return;
      setState((s) => ({ ...s, isConnected: false }));
    });

    // lobby:update — the server sends the full current list of games for the group. 
    // The hook filters out active and finished games to keep only pending ones.
    socket.on('lobby:update', ({ games }: { games: Game[] }) => {
      if (!active) return;
      setState((s) => ({
        ...s,
        pendingGames: games.filter((g) => !g.isActive && !g.isFinished),
      }));
    });

    // game:started — the server broadcasts when a game transitions to active. 
    // The hook only cares if this player is in that game. 
    // This is how select_game knows to navigate the player into the game — 
    // the page watches startedGame and reacts when it becomes non-null.
    socket.on('game:started', ({ game }: { game: Game }) => {
      if (!active) return;
      if (game.players.includes(playerId)) {
        setState((s) => ({ ...s, startedGame: game }));
      }
    });

    return () => {
      active = false;
      socket.disconnect();
    };
  }, [groupId, playerId]);

  return state;
}
