-- AlterTable
ALTER TABLE "GamePlayer" ADD COLUMN "wordsFound" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GamePlayer" ADD COLUMN "freezeCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GamePlayer" ADD COLUMN "completed" BOOLEAN NOT NULL DEFAULT false;
