import type { WordEntry } from '../crossword-words';

export const WORD_POOL: WordEntry[] = [
  { word: 'CAT', clue: 'Feline pet', difficulty: 'easy', tags: ['animals'] },
  { word: 'DOG', clue: 'Loyal canine companion', difficulty: 'easy', tags: ['animals'] },
  { word: 'RAT', clue: 'Small rodent', difficulty: 'easy', tags: ['animals'] },
  { word: 'OWL', clue: 'Wise nocturnal bird', difficulty: 'easy', tags: ['animals'] },
  { word: 'ANT', clue: 'Small colony insect', difficulty: 'easy', tags: ['animals'] },
  { word: 'BEE', clue: 'Honey-making insect', difficulty: 'easy', tags: ['animals'] },
  { word: 'FOX', clue: 'Cunning wild canine', difficulty: 'easy', tags: ['animals'] },
  { word: 'COW', clue: 'Farm animal giving milk', difficulty: 'easy', tags: ['animals'] },
  { word: 'HEN', clue: 'Female chicken', difficulty: 'easy', tags: ['animals'] },
  { word: 'PIG', clue: 'Farm animal known for mud', difficulty: 'easy', tags: ['animals'] },
  { word: 'BEAR', clue: 'Large forest mammal', difficulty: 'easy', tags: ['animals'] },
  { word: 'DEER', clue: 'Graceful forest animal with antlers', difficulty: 'easy', tags: ['animals'] },
  { word: 'FROG', clue: 'Amphibian that jumps', difficulty: 'easy', tags: ['animals'] },
  { word: 'FISH', clue: 'Aquatic creature with fins', difficulty: 'easy', tags: ['animals'] },
  { word: 'WOLF', clue: 'Wild canine that howls', difficulty: 'easy', tags: ['animals'] },
  { word: 'DUCK', clue: 'Waterfowl that quacks', difficulty: 'easy', tags: ['animals'] },
  { word: 'BIRD', clue: 'Feathered flying creature', difficulty: 'easy', tags: ['animals'] },
  { word: 'CRAB', clue: 'Shellfish with claws', difficulty: 'easy', tags: ['animals'] },
  { word: 'LION', clue: 'King of the jungle', difficulty: 'medium', tags: ['animals'] },
  { word: 'TIGER', clue: 'Striped big cat', difficulty: 'medium', tags: ['animals'] },
  { word: 'HORSE', clue: 'Animal ridden for transport', difficulty: 'medium', tags: ['animals'] },
  { word: 'SHEEP', clue: 'Woolly farm animal', difficulty: 'medium', tags: ['animals'] },
  { word: 'SHARK', clue: 'Predatory ocean fish', difficulty: 'medium', tags: ['animals'] },
  { word: 'EAGLE', clue: 'Large bird of prey', difficulty: 'medium', tags: ['animals'] },
  { word: 'SNAKE', clue: 'Legless reptile', difficulty: 'medium', tags: ['animals'] },
  { word: 'WHALE', clue: 'Largest ocean mammal', difficulty: 'medium', tags: ['animals'] },
  { word: 'CAMEL', clue: 'Desert animal with humps', difficulty: 'medium', tags: ['animals'] },
  { word: 'PANDA', clue: 'Black and white bear', difficulty: 'medium', tags: ['animals'] },
  { word: 'MONKEY', clue: 'Primate that swings from trees', difficulty: 'medium', tags: ['animals'] },
  { word: 'RABBIT', clue: 'Small mammal with long ears', difficulty: 'medium', tags: ['animals'] },
  { word: 'PARROT', clue: 'Colourful bird that mimics speech', difficulty: 'medium', tags: ['animals'] },
  { word: 'TURTLE', clue: 'Reptile with a hard shell', difficulty: 'medium', tags: ['animals'] },
  { word: 'DOLPHIN', clue: 'Intelligent marine mammal', difficulty: 'hard', tags: ['animals'] },
  { word: 'PENGUIN', clue: 'Flightless Antarctic bird', difficulty: 'hard', tags: ['animals'] },
  { word: 'GIRAFFE', clue: 'Tallest living land animal', difficulty: 'hard', tags: ['animals'] },
  { word: 'LEOPARD', clue: 'Spotted big cat', difficulty: 'hard', tags: ['animals'] },
  { word: 'GORILLA', clue: 'Largest primate', difficulty: 'hard', tags: ['animals'] },
  { word: 'SUN', clue: 'Star at the centre of our solar system', difficulty: 'easy', tags: ['nature'] },
  { word: 'SKY', clue: 'Overhead expanse above us', difficulty: 'easy', tags: ['nature'] },
  { word: 'SEA', clue: 'Large saltwater body', difficulty: 'easy', tags: ['nature'] },
  { word: 'ICE', clue: 'Frozen water', difficulty: 'easy', tags: ['nature'] },
  { word: 'RAIN', clue: 'Water falling from clouds', difficulty: 'easy', tags: ['nature'] },
  { word: 'TREE', clue: 'Tall woody plant', difficulty: 'easy', tags: ['nature'] },
  { word: 'LEAF', clue: 'Green part of a plant', difficulty: 'easy', tags: ['nature'] },
  { word: 'ROCK', clue: 'Hard mineral mass', difficulty: 'easy', tags: ['nature'] },
  { word: 'SAND', clue: 'Fine grains on a beach', difficulty: 'easy', tags: ['nature'] },
  { word: 'WIND', clue: 'Moving air', difficulty: 'easy', tags: ['nature'] },
  { word: 'SNOW', clue: 'Frozen precipitation', difficulty: 'easy', tags: ['nature'] },
  { word: 'MOON', clue: 'Earth\'s natural satellite', difficulty: 'easy', tags: ['nature'] },
  { word: 'LAKE', clue: 'Inland body of water', difficulty: 'easy', tags: ['nature'] },
  { word: 'HILL', clue: 'Raised landform smaller than a mountain', difficulty: 'easy', tags: ['nature'] },
  { word: 'RIVER', clue: 'Flowing body of fresh water', difficulty: 'medium', tags: ['nature'] },
  { word: 'CLOUD', clue: 'Water vapour mass in the sky', difficulty: 'medium', tags: ['nature'] },
  { word: 'STORM', clue: 'Violent weather event', difficulty: 'medium', tags: ['nature'] },
  { word: 'OCEAN', clue: 'Vast saltwater body', difficulty: 'medium', tags: ['nature'] },
  { word: 'FLAME', clue: 'Visible part of fire', difficulty: 'medium', tags: ['nature'] },
  { word: 'FROST', clue: 'Ice crystals formed on surfaces', difficulty: 'medium', tags: ['nature'] },
  { word: 'FOREST', clue: 'Dense area of trees', difficulty: 'medium', tags: ['nature'] },
  { word: 'DESERT', clue: 'Dry barren landscape', difficulty: 'medium', tags: ['nature'] },
  { word: 'VOLCANO', clue: 'Mountain that can erupt lava', difficulty: 'hard', tags: ['nature'] },
  { word: 'GLACIER', clue: 'Slow-moving mass of ice', difficulty: 'hard', tags: ['nature'] },
  { word: 'TORNADO', clue: 'Rotating column of air', difficulty: 'hard', tags: ['nature'] },
  { word: 'BIT', clue: 'Smallest unit of data', difficulty: 'easy', tags: ['tech'] },
  { word: 'BUS', clue: 'Data transfer pathway in hardware', difficulty: 'easy', tags: ['tech'] },
  { word: 'RAM', clue: 'Volatile memory in computers', difficulty: 'easy', tags: ['tech'] },
  { word: 'CPU', clue: 'Brain of the computer', difficulty: 'easy', tags: ['tech'] },
  { word: 'FILE', clue: 'Named data stored on disk', difficulty: 'easy', tags: ['tech'] },
  { word: 'CODE', clue: 'Instructions written for a computer', difficulty: 'easy', tags: ['tech'] },
  { word: 'DATA', clue: 'Information processed by a computer', difficulty: 'easy', tags: ['tech'] },
  { word: 'BYTE', clue: 'Eight bits of data', difficulty: 'easy', tags: ['tech'] },
  { word: 'DISK', clue: 'Storage medium for data', difficulty: 'easy', tags: ['tech'] },
  { word: 'PORT', clue: 'Connection point for data', difficulty: 'easy', tags: ['tech'] },
  { word: 'LOOP', clue: 'Repeated sequence in code', difficulty: 'easy', tags: ['tech'] },
  { word: 'NULL', clue: 'Absence of value in programming', difficulty: 'easy', tags: ['tech'] },
  { word: 'NODE', clue: 'Point in a network or runtime', difficulty: 'medium', tags: ['tech'] },
  { word: 'ARRAY', clue: 'Ordered collection of elements', difficulty: 'medium', tags: ['tech'] },
  { word: 'CACHE', clue: 'Fast temporary data storage', difficulty: 'medium', tags: ['tech'] },
  { word: 'QUERY', clue: 'Request for data from a database', difficulty: 'medium', tags: ['tech'] },
  { word: 'CLASS', clue: 'Blueprint for objects in OOP', difficulty: 'medium', tags: ['tech'] },
  { word: 'TOKEN', clue: 'Authentication credential', difficulty: 'medium', tags: ['tech'] },
  { word: 'STACK', clue: 'Last-in first-out data structure', difficulty: 'medium', tags: ['tech'] },
  { word: 'PROXY', clue: 'Intermediary server', difficulty: 'medium', tags: ['tech'] },
  { word: 'REDIS', clue: 'In-memory data structure store', difficulty: 'medium', tags: ['tech'] },
  { word: 'REACT', clue: 'JavaScript UI library by Meta', difficulty: 'medium', tags: ['tech'] },
  { word: 'PRISMA', clue: 'TypeScript ORM for databases', difficulty: 'medium', tags: ['tech'] },
  { word: 'DOCKER', clue: 'Container platform for apps', difficulty: 'medium', tags: ['tech'] },
  { word: 'SCHEMA', clue: 'Structure definition for data', difficulty: 'medium', tags: ['tech'] },
  { word: 'SERVER', clue: 'Machine providing services', difficulty: 'medium', tags: ['tech'] },
  { word: 'SOCKET', clue: 'Bidirectional communication channel', difficulty: 'hard', tags: ['tech'] },
  { word: 'PAYLOAD', clue: 'Data carried in a request or message', difficulty: 'hard', tags: ['tech'] },
  { word: 'RUNTIME', clue: 'Environment where code executes', difficulty: 'hard', tags: ['tech'] },
  { word: 'DATABASE', clue: 'Organised collection of structured data', difficulty: 'hard', tags: ['tech'] },
  { word: 'FUNCTION', clue: 'Named block of reusable code', difficulty: 'hard', tags: ['tech'] },
  { word: 'ENDPOINT', clue: 'URL path for an API', difficulty: 'hard', tags: ['tech'] },
  { word: 'VARIABLE', clue: 'Named container for a value', difficulty: 'hard', tags: ['tech'] },
  { word: 'ALGORITHM', clue: 'Step-by-step problem-solving procedure', difficulty: 'hard', tags: ['tech'] },
  { word: 'INTERFACE', clue: 'Contract defining object shape in TypeScript', difficulty: 'hard', tags: ['tech'] },
  { word: 'ACE', clue: 'Top of the deck', difficulty: 'easy', tags: ['general'] },
  { word: 'ART', clue: 'Creative human expression', difficulty: 'easy', tags: ['general'] },
  { word: 'MAP', clue: 'Diagram of a geographic area', difficulty: 'easy', tags: ['general'] },
  { word: 'KEY', clue: 'Device for unlocking doors', difficulty: 'easy', tags: ['general'] },
  { word: 'NET', clue: 'Mesh fabric used in sports', difficulty: 'easy', tags: ['general'] },
  { word: 'CUP', clue: 'Vessel for drinking', difficulty: 'easy', tags: ['general'] },
  { word: 'JAR', clue: 'Glass container with a lid', difficulty: 'easy', tags: ['general'] },
  { word: 'PEN', clue: 'Writing instrument', difficulty: 'easy', tags: ['general'] },
  { word: 'BOX', clue: 'Container with sides and a top', difficulty: 'easy', tags: ['general'] },
  { word: 'GAME', clue: 'Activity done for fun', difficulty: 'easy', tags: ['general'] },
  { word: 'BOOK', clue: 'Bound collection of pages', difficulty: 'easy', tags: ['general'] },
  { word: 'WORD', clue: 'Unit of language', difficulty: 'easy', tags: ['general'] },
  { word: 'PLAY', clue: 'Engage in activity for fun', difficulty: 'easy', tags: ['general'] },
  { word: 'CLUE', clue: 'Hint that leads to an answer', difficulty: 'easy', tags: ['general'] },
  { word: 'GRID', clue: 'Pattern of intersecting lines', difficulty: 'medium', tags: ['general'] },
  { word: 'SCORE', clue: 'Number of points earned', difficulty: 'medium', tags: ['general'] },
  { word: 'TIMER', clue: 'Device that measures elapsed time', difficulty: 'medium', tags: ['general'] },
  { word: 'LEVEL', clue: 'Stage of difficulty in a game', difficulty: 'medium', tags: ['general'] },
  { word: 'PRIZE', clue: 'Reward for winning', difficulty: 'medium', tags: ['general'] },
  { word: 'ROUND', clue: 'One cycle in a game', difficulty: 'medium', tags: ['general'] },
  { word: 'PUZZLE', clue: 'Problem designed to test ingenuity', difficulty: 'medium', tags: ['general'] },
  { word: 'PLAYER', clue: 'Person taking part in a game', difficulty: 'medium', tags: ['general'] },
  { word: 'ANSWER', clue: 'Response to a question', difficulty: 'medium', tags: ['general'] },
  { word: 'LETTER', clue: 'Character of the alphabet', difficulty: 'medium', tags: ['general'] },
  { word: 'RIDDLE', clue: 'Puzzling question with a clever answer', difficulty: 'medium', tags: ['general'] },
  { word: 'LANGUAGE', clue: 'System of human communication', difficulty: 'hard', tags: ['general'] },
  { word: 'CROSSWORD', clue: 'Word puzzle on a numbered grid', difficulty: 'hard', tags: ['general'] },
  { word: 'CHALLENGE', clue: 'Difficult task requiring effort', difficulty: 'hard', tags: ['general'] },
  { word: 'SOLUTION', clue: 'Answer to a problem or puzzle', difficulty: 'hard', tags: ['general'] },
  // German words with umlauts and German-specific vocabulary
  { word: 'KÄSE', clue: 'German dairy product with holes', difficulty: 'medium', tags: ['german', 'food'], language: 'de' },
  { word: 'SCHÖN', clue: 'German word meaning beautiful', difficulty: 'medium', tags: ['german', 'adjective'], language: 'de' },
  { word: 'GRÖSSE', clue: 'German word for size', difficulty: 'hard', tags: ['german'], language: 'de' },
  { word: 'FLÜSSE', clue: 'German plural of river', difficulty: 'hard', tags: ['german', 'nature'], language: 'de' },
  { word: 'MÜLLER', clue: 'German surname meaning miller', difficulty: 'medium', tags: ['german'], language: 'de' },
  // French words with accents and French-specific vocabulary
  { word: 'CAFÉ', clue: 'French word for coffee', difficulty: 'easy', tags: ['french', 'food'], language: 'fr' },
  { word: 'ÉLÈVE', clue: 'French word for student', difficulty: 'medium', tags: ['french'], language: 'fr' },
  { word: 'CHÂTEAU', clue: 'French word for castle', difficulty: 'medium', tags: ['french', 'building'], language: 'fr' },
  { word: 'FAÇADE', clue: 'French architectural term for building front', difficulty: 'hard', tags: ['french'], language: 'fr' },
  { word: 'CRÈME', clue: 'French word for cream', difficulty: 'medium', tags: ['french', 'food'], language: 'fr' },
  { word: 'ÊTRE', clue: 'French verb meaning to be', difficulty: 'easy', tags: ['french'], language: 'fr' },
];
